### ISSUE TITLE
My scheduled task does not start

### ISSUE THREAD

**Issue by cabrasm** [aldeed/meteor-scheduled-tasks#3]
Hello!

First, thanks for all your packages, life's much easier!
I've got a simple scheduled task which removes passed events in my apps with a single query (tested) and it should run on server side with the startup method. 

Meteor.startup(function () {
	console.log("StartUp function...");
	schedTask.start();
	console.log("Scheduled Task started...")
});

var schedTask = new ScheduledTask('at 02:40pm every day ', function() {
	console.log("Every activity before " + new Date() + " will be erased...");
	Activities.find( {"activityDate" : { "$lt" : new Date() } } ).forEach( function(row) {
		Activities.remove({_id : row._id});
	});
});

When I start my meteor app, on the debug console i see "StartUp function..." then "Scheduled Task started..." but nothing happens...

Do I do something wrong? 

Thanks in advance

**Comment by mvgalle** [comment]
I had a similar problem. It could be a timezone problem, the default for later is UTC. 
Try something like this outside your startup function, still on the server in your startup.js file:

var scheduleEveryDay = later.parse.recur().on('14:40:00').time();
later.date.localTime();
functionToRun = function() {
    console.log("I ran this function.");
};

Meteor.startup(function () {
var myScheduledTask = new ScheduledTask(scheduleEveryDay, functionToRun);
myScheduledTask.start();
}

**Comment by aldeed** [comment]
I don't maintain this package anymore. I think `percolatestudio:synced-cron` is a better solution, and there are a few others as well.

**Comment by 2lazy2debug** [comment]
Hello!
Well, it was more a server-side problem. The task started like 20-30 minutes after the time I gave.
Actually, it's a shame that you don't mantain it anymore, was a good one!
